### ISSUE TITLE
Esri Mapp Your Way 4.0 Winning Post 

### ISSUE THREAD

**Issue by abhishekvp** [gcsl-csre-iitb/labWebsite#1]

**Comment by abhishekvp** [comment]
Add Photo too. Refer http://www.geosysiot.in/2016/12/18/team-wins-esri-indias-national-level-app-development-challenge/

**Comment by omshinde** [comment]
Link for the update: http://www.geosysiot.in/2019/01/08/team-wins-esri-indias-mapp-your-way-4-0/
