### ISSUE TITLE
WCDM Post - Exhibition

### ISSUE THREAD

**Issue by abhishekvp** [gcsl-csre-iitb/labWebsite#4]
Add Photo

**Comment by aarifsk** [comment]
Description added. Photo addition pending.

**Comment by omshinde** [comment]
Link to the update: http://www.geosysiot.in/2019/01/31/deepdisasternet-paper-presentation-at-the-4th-world-congress-on-disaster-management/?preview_id=536&preview_nonce=5f68db1470&preview=true&_thumbnail_id=554
